### ISSUE TITLE
Provide hosting for complete dataset 

### ISSUE THREAD

**Issue by akachru-github** [imicroseq/roadmap#10]
- Create zip file of total FASTA and METADATA that @lindaxiang will create: https://github.com/cancogen-virus-seq/roadmap/issues/14
- Collab, public READ, URL. 

@caravinci , once done, you should be able to use this URL for eventual DOWNLOAD ALL button.

**Comment by christinayung** [comment]
Bucket created: https://console.cancercollaboratory.org/project/containers/container/Download/data
Download URL: https://object.cancercollaboratory.org:9080/swift/v1/Download/data/[file name]

**Comment by christinayung** [comment]
URL for "Download All": 
https://object.cancercollaboratory.org:9080/swift/v1/Download/data/virusseq_metadata_consensus_all_20210427.tgz

Downloaded this successfully after disconnect from VPN.
