### ISSUE TITLE
Submission UI - miss `Study ID` 

### ISSUE THREAD

**Issue by lindaxiang** [imicroseq/roadmap#13]
Here is the example:
![Screen Shot 2021-04-23 at 8 23 53 PM](https://user-images.githubusercontent.com/7522294/115941115-11fdba00-a472-11eb-91d0-8471c79b6e51.png)

**Comment by lindaxiang** [comment]
Also it will be nicer to include `submitted metadata filename` listed in the submission table.

**Comment by rosibaj** [comment]
![image](https://user-images.githubusercontent.com/15824252/117185942-5e1cf880-ada8-11eb-8a1a-ab8539d664c2.png)
 Can see on Ui looks great! thank you @caravinci @jaserud !
