### ISSUE TITLE
Consistent file naming scheme for download files

### ISSUE THREAD

**Issue by christinayung** [imicroseq/roadmap#16]
Change the file naming scheme under Download to more consistent formats:
* Metadata Table: `virusseq-table-export-20210426.tsv` --> `virusseq-metadata-export-2021-04-26T14_01_29.552108Z`
* Consensus Seq: `sample-bundle-2021-04-26T14_01_29.552108Z.fasta` --> `virusseq-consensus-export-2021-04-26T14_01_29.552108Z`
* Consensus Seq (gz): `virusseq-consensus-export-2021-04-26T14_01_33.704719Z.fasta.gz`

**Comment by rosibaj** [comment]
![image](https://user-images.githubusercontent.com/15824252/116155434-14e9ec00-a6b8-11eb-969c-108a7390de51.png)

consensus files look good; metadata file not quite there:

@jaserud for the table, can we get it adjusted to `virusseq-metadata-export-2021-04-26T14_01_29.552108Z` as above table --> metadata.
