### ISSUE TITLE
BE: UI for curators to manage users - Permission Granting Service

### ISSUE THREAD

**Issue by rosibaj** [imicroseq/roadmap#17]
Service with 2 functions that Simon Fraser can use:
- [ ] Create Study: Creates the correct policy in Ego, Creates a user group in ego, Creates the study in Song
- [ ] Add/remove users to study:  Adds an email/study combo of users to  the correct ego group

- [ ] Create New policy for study administratoin e.g `VIRUSSEEQ-STUDYADMIN`
- [ ] @kcullion talk with Rosi to design the study/user addition

**Comment by jaserud** [comment]
Deploy instructions:
- update helm values like dev
- update terraform config `.tfvars` as is in dev
- run terraform job
- apply network policy for service

**Comment by rosibaj** [comment]
- created a study, and added users and it looks ok from the front end: 
![image](https://user-images.githubusercontent.com/15824252/122936748-653f9c00-d33f-11eb-9929-451d5d7c21dd.png)
- was able to login with fakerosi email and submit data
![image](https://user-images.githubusercontent.com/15824252/122939929-0891b080-d342-11eb-96b1-77e714bd0cfa.png)


no issues with user/study creation. moving to awaiting release - thank you @jaserud !
