### ISSUE TITLE
Make users aware of acknowledging the contributors - Modal Dialog

### ISSUE THREAD

**Issue by akachru-github** [imicroseq/roadmap#19]
Modal proposal
- When you download any data from the portal (table, or DOWNLOAD ALL), a modal pops up saying "Your download has started. By downloading this data, you agree to acknowledge the contributors listed here **[[URL]]**."
- Download will start right away. This modal does not gate the download.

**Comment by rosibaj** [comment]
@jaserud I have a new text update for this modal as follows:
------

Your download has started. By downloading this data, you agree to [acknowledge]( https://virusseq-dataportal.ca/acknowledgements) the Canadian Public Health Laboratory Network (CPHLN), CanCOGeN VirusSeq, all laboratories having contributed data and follow all [CVDP policies](https://virusseq-dataportal.ca/policies).

Data that is being shared is the work of many individuals and should be treated as unpublished data. If you wish to publish research using the data, contact us at info@virusseq-dataportal.ca  first to ensure that those who have generated the data can be involved in its analysis.


-----
links:
- https://virusseq-dataportal.ca/acknowledgements
- https://virusseq-dataportal.ca/policies

**Comment by rosibaj** [comment]
@jaserud one small change on the link color:
![image](https://user-images.githubusercontent.com/15824252/120239505-6f80e580-c22c-11eb-8e01-8e56d61f4d1d.png)

**Comment by rosibaj** [comment]
lgtm thank you @jaserud !

**Comment by rosibaj** [comment]
- acknowledgements hyperlink removed for now as acknowledgements page is not ready
- confirmed on production
