### ISSUE TITLE
FE: UI for curators to manage users

### ISSUE THREAD

**Issue by akachru-github** [imicroseq/roadmap#21]
- create a new policy/group and add users to the group
- review the list of users in a study
- review the list of studies that a user is in
- Similar to program service interface
  - keep this simple, it is for curators only. 

## Expected Outcomes for UI

- [x] **Add item at top of user dropdown** to access the "Manage Studies" section: https://zpl.io/VQNgoxR
--------------------------------------
- [x] **Build the table** that lists all of the studies: https://zpl.io/2GjepgW
This includes:
- default sort descending alpha order by study id
- if possible, sort the data submitters in alpha order too within each row
- add a blue line to separated the studies and lines to separate the data submitters
- the global action buttons above the table for creating a study and adding data submitters
--------------------------------------
- [x] **Build the Create a Study modal**: https://zpl.io/ag3M9yQ
This includes:
- display this modal when the curator clicks the `create a study` button
- validation for the required fields (these errors can appear when the user interacts with the field and then clicks away from it, unless you have other ideas!) https://zpl.io/bARYA0B
- validation for study id to limit the field to 15 characters: https://zpl.io/aR4QovE
- `Create study` button is only enabled once the curator fills out the form correctly
--------------------------------------
- [x] **Build the Add Data Submitters modal**: https://zpl.io/bJDYPZK
This includes:
- display this modal when the curator clicks the `add data submitters` button
- the study id field is a type ahead look-up field. The curator has to choose from the study ids that already exist: https://zpl.io/a8nYOww
- the email field is a type ahead look-up field. The curator has to choose from email addresses that are already registered in the portal: https://zpl.io/aX7dQP8
- Once the curator adds one email address, the "Add another" button is enabled and they can continue adding more email addresses. Each email address (except for the first one) can also be removed from this modal by clicking the trashcan icon: https://zpl.io/a7PYqWW
- validation for the required fields. For example, if the curator deleted the study id they would see an error to fill that out and the `Add Data Submitters` button would disable: https://zpl.io/aw3j7gJ
- `Add Data Submitters` button is only enabled once the curator fills out the form correctly
--------------------------------------
- [x] **Success:** Adding study/data submitters to the table: https://zpl.io/bARYvPO
This includes:
- When a study is created, display the success banner at the top (dismissible): https://zpl.io/aNxRprD
- Add the study and metadata to the table
- When a data submitter is added to a study, display the success banner at the top (dismissible): https://zpl.io/bARYvPO
- Add each email address to the study row data submitters column
--------------------------------------
- [x] **Error:** Adding study/data submitters to the table: https://zpl.io/VKdY0r6
This includes:
- If an error exists when creating a study or adding data submitters, display an error banner above the table. For example: if the curator tries to add a study that has the same Study ID as one that already exists
--------------------------------------
- [x] **Removing a user from a study:**
This includes:
- build the confirmation modal that appears when the curator clicks the trashcan icon beside a data submitter: https://zpl.io/bW8DYQ1
- When the curator confirms this, display the success banner and remove that data submitter from the study row: https://zpl.io/2p3ZDN8
- --------------------------------------
- [x] **Data Curator profile page:** https://zpl.io/ag3MZyO
This includes:
- display a `Data Curator` badge beside their name
- for the study access section, display "All Studies" as their access level

**Comment by akachru-github** [comment]
reach out to @kcullion for design.

**Comment by akachru-github** [comment]
Reviewed the functionality with @rosibaj and @kcullion. 
This ticket is now focused on just the UI development. Designs are being worked on now. 
The BE portion is being tracked here: https://github.com/cancogen-virus-seq/roadmap/issues/17

**Comment by rosibaj** [comment]
@jaserud just a couple small things to fix:

- [x] the font is different on the text box
![image](https://user-images.githubusercontent.com/15824252/122933639-d29dfd80-d33c-11eb-9301-fab679d82eee.png)

-  [ ] Fix the spacing on the input boxes on create study form)
![image](https://user-images.githubusercontent.com/15824252/122933606-cade5900-d33c-11eb-95fe-23114da20215.png)

**Comment by rosibaj** [comment]
@jaserud just going to move back to in progress for these small changes!
