### ISSUE TITLE
UI: Make users aware of acknowledging the contributors - Contributors page

### ISSUE THREAD

**Issue by akachru-github** [imicroseq/roadmap#22]
- Create page that lists all contributors to Virus-Seq data
- Generate nightly a list of contributors from the “Sample Collected By” and “Sample Submitted By” columns, and put on an Acknowledgement page with a “last updated on XX”.
- Single set of data, sorted alphabetically, comma separated.
- This ticket includes 
  - The generation of JSON containing all contributors. Can be stored in Object Storage. Python script used to generate. 
  - Page  to display the contributor data.

**Comment by akachru-github** [comment]
- 1 unified list. 
- "Not provided" will be filtered out.

**Comment by rosibaj** [comment]
Content for page:

----------

## Acknowledgement of Contributions 
_Updated on [Date]_

The Canadian VirusSeq initiative requests that authors who use data from the portal acknowledge the contributions of Canadian researchers in the acknowledgements section of their work. An example of a proper acknowledgement is:

"The results <published or shown> here are in whole or part based upon data hosted at the Canadian VirusSeq Data Portal: https://virusseq-dataportal.ca/explorer."

Authors are encouraged to recognize the contribution of the appropriate specimens and research groups based on the dataset used in research.  

The following members have contributed data to the Canadian VirusSeq Data Portal: 

Contributor 1
Contributor 2
Contributor 3

**Comment by rosibaj** [comment]
@lepsalex we have a content update for this page under the `website content` section: 
https://docs.google.com/document/d/17wzrMr4EQ0qJiKSEAl7Kkg4PuoW_gMi_a8cP7pyETwE/edit# 

you should be able to access this doc but let me know if you have any issues.

**Comment by rosibaj** [comment]
@lepsalex as this page was not yet ready, i had to remove a hyperlink to it.  When the page is available in the UI in this ticket, can you please add the hyperlink back in the confirmation modal like so:


>Your download has started. By downloading this data, you agree to [acknowledge](https://virusseq-dataportal.ca/acknowledgements) the Canadian Public Health Laboratory Network (CPHLN), CanCOGeN VirusSeq, all laboratories having contributed data and follow all CVDP policies.
...

links:

https://virusseq-dataportal.ca/acknowledgements

**Comment by rosibaj** [comment]
- tested page and it is rendering the correct content
- tested modal and it is rendering the link correctly as well (going to prod currently but should work on deploy!) 

thank you @lepsalex !
