### ISSUE TITLE
Update ES mapping with new fields

### ISSUE THREAD

**Issue by lindaxiang** [imicroseq/roadmap#26]
The following new fields will need to be added to the ES mapping file: 
1. `gene_name`
2. `diagnostic_pcr_ct_value`
3. `sample_collection_date_null_reason`
4. `host_age_null_reason`
5. `fasta_header_name`

**Comment by lindaxiang** [comment]
- [x]  remove the following fields from mapping as we are not going to expect them in the submitted TSV

1. sample collection date precision
2. NML submitted specimen type
3. Ns per 100 kbp
4. consensus genome length
5. geo_loc_name (city)
6. library ID
7. lineage/clade analysis software name
8. lineage/clade analysis software version
9. lineage/clade name
10. sequencing date
11. variant designation
12. variant evidence
13. variant evidence details

- [x] rename field `sequencing protocol name` to `sequencing protocol` in mapping

**Comment by rosibaj** [comment]
https://github.com/cancogen-virus-seq/infra/pull/41

**Comment by rosibaj** [comment]
prod update: https://github.com/cancogen-virus-seq/infra/pull/42 

Redindexing has begin.
