### ISSUE TITLE
Archive design

### ISSUE THREAD

**Issue by rosibaj** [imicroseq/roadmap#28]
Wiki to describe 

- Database design for archives 
- Connection between DB and bundle delivery 
- Design for build interactions + scalability
  - should a build be initiated?
  - in scaled instances, which worker node is responsible for coordinating the build in a primary/secondary?
  - in scaled instances, can we use a postgres status relationship WITH ES latest updated data in a transactional relationship to ensure one build at a time.

**Comment by lepsalex** [comment]
https://wiki.oicr.on.ca/display/OV/CanCoGen+Virus+Seq+Data+Portal#CanCoGenVirusSeqDataPortal-4.4.1DataDownloadandAggregation-HighLevel

**Comment by rosibaj** [comment]
@lepsalex 👍 read through; no questions.
