### ISSUE TITLE
Submit Data Issue - Nothing happened after click `Submit Data` button

### ISSUE THREAD

**Issue by lindaxiang** [imicroseq/roadmap#9]
- I login the Submission UI, upload the files and have the following:
<img width="848" alt="Screen Shot 2021-04-22 at 10 45 02 AM" src="https://user-images.githubusercontent.com/7522294/115739897-526b1400-a35c-11eb-8857-74f35ef55929.png">

-Then I click the `Submit Data` and get the following:
<img width="487" alt="Screen Shot 2021-04-22 at 10 42 19 AM" src="https://user-images.githubusercontent.com/7522294/115739857-4a12d900-a35c-11eb-9bab-b0b67f9050ff.png">

- But there is nothing happen after, still show me the following:
<img width="848" alt="Screen Shot 2021-04-22 at 10 45 02 AM" src="https://user-images.githubusercontent.com/7522294/115740125-85ada300-a35c-11eb-9e2a-58e9a18d0341.png">

**Comment by justincorrigible** [comment]
Were you able to see any error messages in the `console` or `network` devtools panels?

**Comment by justincorrigible** [comment]
Resolved as "The user didn't have enough access/permissions"
